---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: Copy mariadb to yum 
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0777
       #copy task copies what is in the db folder into etc folder

    - name: Dl MariaDB server
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present
      #apt was the orginal cmd, change to yum because that is the package manager
      #installs mariaDB 

    - name: Unpack db.tgz to localhost
      unarchive: src=db/db.tgz dest=~/ mode=0777
      #unpacks and open the 

    - name: Make DB
      become:yes 
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
      #cd backs into old dir; ignore_errors ignores any errors that do occur
      # change the dns name
