---
- hosts: db
  vars:
  tasks:
  - name: include vars
    include_vars: vault.yml

  - name: Add MariaDB repo to yum repo
    become: true
    copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644
  
  - name: Download MariaDB client
    become: yes
    package: name=MariaDB-client update_cache=yes state=present
  
  - name: Unarchive the database files
    become: true
    unarchive: src=db/db.tgz dest=~/ mode=0777

  - name: Make DB
    become: yes
    command: ./make_databases.sh {{ db_password }} db.ctu2uhkiqqiy.us-west-2.rds.amazonaws.com chdir=~/db
    ignore_errors: True
      #cd backs into old dir; ignore_errors ignores any errors that do occur
      # change endpoint for db each it is destroyed
